server:
  port: ${PORT:8088}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8088}

spring:
  datasource:
    url: ${DB_URL}  ## Cambiar "model" por tu base de datos
    username: ${DB_USERNAME}  ## Cambiar por tu usuario
    password: ${DB_PASSWORD}  ## Cambiar por tu contraseña
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Puede ser 'create', 'update', 'validate' o 'none'
    show-sql: false  # Puede true o false, para ver las consultas SQL en consola
  jackson:
    serialization:
      indent-output: true # Formatea el JSON de salida

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8088/swagger-ui.html